src/constants/shuttle.ts
src/handler.ts
src/service/NoticeService.ts
src/service/ShuttleService.ts

깃허브 사용 연습,,
셔틀 하드 코딩,,
테스트 불가,,,

셔틀 버스 하드 코딩, 셔틀버스 api 추가 테스트 중

---

README.md

README 수정했습니다.

---

serverless.yml
src/constants/calendar.ts
src/constants/shuttle.ts

mainPlan 수정

---

serverless.yml

handler error

---

src/handler.ts

return function add await

---

src/service/weather.service.ts

weather값 문자열로 수정

---

src/service/weather.service.ts

날씨 result에 단위 추가했습니다.

---

serverless.yml
src/handler.ts
src/service/diet.service.ts
test/diet.test.ts

기숙사 식단 추가하였습니다.

---

src/service/BusService.ts
src/service/diet.service.ts

주말일때 식단 결과가 2021년 12월 04일로 날짜 형식으로 값이 오던걸 빈배열로 수정하였습니다.

식단 주말일때 빈배열로 보내도록 수정

---

.vscode/settings.json
src/service/diet.service.ts

식단 반영안되던 버그 해결

---

src/service/diet.service.ts

- 학생식당 에러 수정하였습니다.(html 태그가 같이 보이는 에러)
- 식단 없던 부분 임시 수정하였습니다.

학생식당 수정하였습니다.

---

src/service/diet.service.ts
test/diet.test.ts

중식 없을 시 식단 밀려나오는 버그 수정

---

src/service/diet.service.ts

- 기숙사 메뉴 구분 오류 수정
- thead에 따라 tbody 위치 결정

modify: 기숙사 식단 메뉴별 구분, 로직 수정

---

package-lock.json
package.json
src/handler.ts
src/routes/busRouter.ts
src/routes/calendarRouter.ts
src/routes/dietRouter.ts
src/routes/noticeRouter.ts
src/routes/shuttleRouter.ts
src/routes/timeTableRouter.ts
src/routes/weatherRouter.ts
test/diet.test.ts
test/shuttle.test.ts
test/weather.test.ts

타입 없는거 추가하였습니다.

---

serverless.yml

1. `serverless.yml` frameworkVersion을 3으로 수정하였습니다.

serverless frameworkVersion 3으로 수정

---

src/service/DietService.ts

modify : 식단 공백 아이템 제거

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
package-lock.json
package.json

1.`serverless` 패키지들이 문제가 되어서 삭제하였습니다.

fix: serverless 삭제하였습니다.

---

src/routes/calendarRouter.ts
src/routes/homeRouter.ts
src/service/CalendarService.ts
src/util/parseCalendarRawText.ts
src/util/parseNumber.ts
test/calendar.test.ts

API 명세는 노션 참고해주세요
https://www.notion.so/API-3cee7bc4c480431d8bcbb4bad05ead0a

학사일정 API 구현

---

README.md
src/routes/busRouter.ts
src/routes/dietRouter.ts

docs: README에 홈, 버스 응답 추가

---

src/logger.ts
src/routes/busRouter.ts
src/routes/dietRouter.ts
test/bus.test.ts

fix: log 설정 실시간으로 모니터링 할 수 있도록 수정

---

src/routes/busRouter.ts
src/service/BusServiceNew.ts

fix: carno string으로 변경

---

README.md
src/constants/function/commonfunction.ts
src/routes/busRouter.ts
src/routes/dietRouter.ts
src/routes/homeRouter.ts
src/service/BusServiceNew.ts
src/service/DietService.ts

1. 주변 정류장 리팩토링하였습니다.
2. home에 dayType을 추가하였습니다.
3. 식단에 장소필터를 추가하였습니다.

주변 정류장 리팩토링, home에 dayType추가, 식단에 장소필터 추가

---

README.md
src/constants/function/commonfunction.ts
src/routes/homeRouter.ts
src/service/BusServiceNew.ts
src/service/mainService.ts

dayType 함수 구현, departBusNext 타임존 수정

dayType 함수 구현, departBusNext 타임존 수정

---

src/service/weatherService.ts

fix: weather 빈 값 캐싱 되지 않도록 수정
